### ISSUE TITLE
Snippet to create a complete 'describe / it / expect' skeleton

### ISSUE THREAD

**Issue by Holf** [deinsoftware/vscode-vitest-snippets#15]
I love this extension and it saves me time every day.

I wonder if an additional snippet might be helpful, that sets up a new test file with the skeleton necessary to write your first test?

For example:

```JavaScript
import { describe, expect, it } from "vitest";

describe("group ", () => {
	it("should ", () => {
		expect(true).toBe(true);
	});
});
```

**Comment by equiman** [comment]
I would try to take a look this weekend!

**Comment by equiman** [comment]
Version `1.8.0` was deployed.

Take a look on skeleton section: 

https://marketplace.visualstudio.com/items?itemName=deinsoftware.vitest-snippets#skeleton

**Comment by Holf** [comment]
Fantastic! Thank you so much. 🙂
